// src/constants/strings.ts
// All user-facing static text in one place.
// Prepared for future i18n: replace this file with a locale-aware equivalent
// (e.g. i18next, expo-localization) without touching any component.

export const Strings = {
  // ─── Common ──────────────────────────────────────────────────────────────
  common: {
    cancel:       'Cancel',
    save:         'Save',
    delete:       'Delete',
    edit:         'Edit',
    done:         'Done',
    back:         'Go back',
    viewAll:      'View All →',
    loading:      'Loading...',
    error:        'Error',
    confirm:      'Are you sure?',
  },

  // ─── Errors ───────────────────────────────────────────────────────────────
  errors: {
    notFound:        'Record not found',
    loadFailed:      'Failed to load data',
    saveFailed:      'Failed to save',
    deleteFailed:    'Failed to delete',
    updateFailed:    'Failed to update',
    generic:         'Something went wrong',
  },

  // ─── Habits ───────────────────────────────────────────────────────────────
  habits: {
    screenTitle:       'Habit Tracker',
    activeTimers:      'Active Timers',
    recentSessions:    'Recent Sessions',
    startTimer:        'Start Timer',
    stopTimer:         'Stop Timer',
    liveBadge:         'LIVE',
    emptyTimers:       'No Active Timers',
    emptyTimersDesc:   'Start tracking your activities',
    emptySessions:     'No Sessions Yet',
    emptySessionsDesc: 'Complete activities to see them here',
    deleteTitle:       'Delete Session',
    deleteMessage:     'Are you sure you want to delete this session?',
    deleteError:       'Failed to delete session',
    notFound:          'Session not found',
    detailTitle:       'Session Details',
  },

  // ─── Finance ──────────────────────────────────────────────────────────────
  finance: {
    screenTitle:       'Finance Tracker',
    recentTitle:       'Recent Transactions',
    analyticsTitle:    'Analytics',
    addTitle:          'Add Transaction',
    detailTitle:       'Transaction Details',
    income:            'Income',
    expense:           'Expense',
    balance:           'Balance',
    totalIncome:       'Income',
    totalExpenses:     'Expenses',
    transactions:      'Transactions',
    average:           'Average',
    byCategory:        'Expenses by Category',
    largestTitle:      'Largest Transactions',
    largestIncome:     'Largest Income',
    largestExpense:    'Largest Expense',
    financialInsight:  'Financial Insight',
    emptyTitle:        'No Transactions Yet',
    emptyDesc:         'Start tracking your finances',
    deleteTitle:       'Delete Transaction',
    deleteMessage:     'Are you sure you want to delete this transaction?',
    deleteError:       'Failed to delete transaction',
    notFound:          'Transaction not found',
  },

  // ─── Diary ────────────────────────────────────────────────────────────────
  diary: {
    screenTitle:       'My Diary',
    recentEntries:     'Recent Entries',
    thisMonth:         'This Month',
    newEntry:          'Write Entry',
    calendarView:      'Calendar View',
    detailTitle:       'Diary Entry',
    statsEntries:      'Entries',
    statsThisWeek:     'This Week',
    statsTotalWords:   'Total Words',
    streakLabel:       'day streak',
    contentLabel:      'Content',
    titleLabel:        'Title',
    titlePlaceholder:  'Entry title...',
    contentEmpty:      'Content cannot be empty',
    emptyTitle:        'No Entries Yet',
    emptyDesc:         'Start journaling your thoughts and experiences',
    deleteTitle:       'Delete Entry',
    deleteMessage:     'Are you sure you want to delete this diary entry? This action cannot be undone.',
    deleteError:       'Failed to delete entry',
    updateError:       'Failed to update entry',
    notFound:          'Entry not found',
    entryInsight:      'Entry Insight',
    insightBrief:      'A brief reflection. Every word counts in capturing your moment.',
    insightThoughtful: "A thoughtful entry. You've captured the essence of your day.",
    insightDetailed:   "A detailed reflection. You've given good depth to your thoughts.",
    insightExtensive:  "An extensive journal entry! You've really explored your experiences.",
  },

  // ─── Leisure ──────────────────────────────────────────────────────────────
  leisure: {
    screenTitle:       'Leisure Tracker',
    activeSession:     'Active Session',
    recentSessions:    'Recent Sessions',
    todayStats:        "Today's Stats",
    statsSessions:     'Sessions',
    statsTotalTime:    'Total Time',
    statsAllTime:      'All Time',
    startSession:      'Start Session',
    stopSession:       'Stop',
    detailTitle:       'Session Details',
    timeDetails:       'Time Details',
    labelStarted:      'Started',
    labelEnded:        'Ended',
    labelDuration:     'Duration',
    labelTotalDuration:'Total Duration',
    sessionInsight:    'Session Insight',
    insightQuick:      'Quick session! Perfect for a short break.',
    insightNice:       'Nice session length. Good balance.',
    insightExtended:   'Extended session! Take breaks.',
    insightLong:       'Long session! Stay hydrated and stretch.',
    emptyTitle:        'No Sessions Yet',
    emptyDesc:         'Start tracking your leisure time',
    deleteTitle:       'Delete Session',
    deleteMessage:     'Are you sure you want to delete this session?',
    deleteError:       'Failed to delete session',
    notFound:          'Session not found',
  },

  // ─── Settings ─────────────────────────────────────────────────────────────
  settings: {
    screenTitle: 'Settings',
    theme:       'Theme',
    darkMode:    'Dark Mode',
    lightMode:   'Light Mode',
    language:    'Language',
    sync:        'Sync',
    about:       'About',
  },
} as const;
